apiVersion: v1
kind: Service
metadata:
  name: redesocial-backend
  labels:
    run: redesocial-backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: redesocial-backend