apiVersion: v1
kind: Service
metadata:
  name: rede-social-frontend
  labels:
    run: rede-social-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: rede-social-frontend