apiVersion: apps/v1
kind: Deployment
metadata:
  name: rede-social-db
  labels:
    app: rede-social-db
spec:
  selector:
    matchLabels:
      app: rede-social-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rede-social-db
    spec:
      containers:
      - name: rede-social-db
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
        env:
          # --- Dados Sensíveis vindo do Secret ---
          - name: MYSQL_ROOT_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: rede-social-db-secrets
                key: MYSQL_ROOT_PASSWORD
          
          - name: MYSQL_USER 
            valueFrom:
              secretKeyRef:
                name: rede-social-db-secrets
                key: DB_USER # Usando a mesma chave criada no exemplo anterior
          
          - name: MYSQL_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: rede-social-db-secrets
                key: DB_PASSWORD
          
          # --- Dados Não Sensíveis vindo do ConfigMap ---
          - name: MYSQL_DATABASE 
            valueFrom:
              configMapKeyRef:
                name: rede-social-db-configmap
                key: DB_NAME
                
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        volumeMounts:
          - name: rede-social-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: rede-social-persistent-storage
          persistentVolumeClaim:
            claimName: rede-social-pv-claim