apiVersion: v1
kind: Secret
metadata:
  name: redesocial-db-secrets
type: Opaque
stringData:
  DB_USER: user_app
  DB_PASSWORD: change_me_user
  MYSQL_ROOT_PASSWORD: change_me_root
  JWT_SECRET: a2c4e6858c1b4e29a3f2d8e5g1h3i5j7k9l2m4n6o8p1q3r5s7t9u1v3w5x7y9z0a2b4
