apiVersion: v1
kind: Service
metadata:
  name: rede-social-db
  labels:
    run: rede-social-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: rede-social-db