apiVersion: v1
kind: Service
metadata:
  name: redesocial-db
  labels:
    run: redesocial-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: redesocial-db