apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-{{ .Values.global.backend.name}}
  labels:
    app: {{.Release.Name}}-{{ .Values.global.backend.name}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}-{{ .Values.global.backend.name}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{ .Values.global.backend.name}}
    spec:
      containers:
        - name: {{.Values.global.backend.name}}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-db-configmap
                  key: DB_HOST
            
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-db-configmap
                  key: DB_NAME

            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-db-configmap
                  key: JWT_EXPIRATION
                  optional: true 

            - name: APP_CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-db-configmap
                  key: APP_CORS_ALLOWED_ORIGINS

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-db-secrets
                  key: DB_USER
            
            - name: DB_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-db-secrets
                  key: DB_PASSWORD

            - name: JWT_SECRET 
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-db-secrets
                  key: JWT_SECRET

          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"